version: '3'

services:
  portus:
    image: docker pull opensuse/portus:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      
networks:
  frontend:
    driver: overlay
